captureDirectory: ./captures
completeDirectory: ./captures
modelScanInterval: 30
createModelDirectory: true
dateFormat: YYYYMMDD-HHmmss
minFileSizeMb: 10
port: 9080
debug: false
models: 
  - uid: 14092496
    mode: 1
    nm: LauraVega
queue: []
rtmp: false
